export const FORTUNES = [
  "Money is waiting for you — it's time to open the door.",
  "This year love won’t send you a letter, but a warm scarf. Your emotions are growing stronger.",
  "Your career path is becoming clear — you are finally on your own path.",
  "The mirror no longer just looks at you, it applauds you. You are shining.",
  "Your luck will shine so brightly that every step you take will glow.",
  "One cup of hot tea = one step closer to your wish.",
  "Destiny whispers: 'When you're ready, so am I.'",
  "This year brings a little magic, a little courage, and a hint of cinnamon. You are entering abundance.",
  "If your wish comes true, don’t be surprised. If it doesn’t, something better is coming.",
  "The universe is winking at you. Stay alert to the signs.",
  "Money is now flowing according to your plan.",
  "Love has found you this year — just open your arms.",
  "This year, you will personally see the quality of your work.",
  "The smile on your face will be your strongest magic.",
  "Money is no longer leaving you — it stays by your side.",
  "Love gives you answers, not questions. Add love to your work.",
  "Slowly but steadily, you are moving forward.",
  "New pages are opening in your life — may the changes serve your highest good.",
  "This year your appearance shines together with your inner glow.",
  "Choosing yourself is not selfishness — it is self-care.",
  "Money flows in rhythm with you.",
  "The strongest magic: consistency and calmness.",
  "What is meant for you stays with you. Let the rest go.",
  "What belongs to you is already coming — you just need to set the meeting.",
  "You are finally stepping out of the whirlwind. Congratulations.",
  "I think you already know the answer. Maybe it's time to take action? ;)",
  "This year, trusting yourself will guide you.",
  "New beginnings are waiting for you.",
  "Your wish has been accepted — the universe just says 'loading...'",
  "The sound of rain carries a message: the right path is quiet, not loud.",
  "The smile on your face will be your strongest manifestation this year.",
  "This year money flows not into pockets, but into plans. Make your plan.",
  "Love this year is like hot tea — drink it slowly and savor the taste.",
  "This year’s best decision will be listening to yourself.",
  "Trust your inner voice. All the answers are right in front of you.",
  "Your path is becoming clearer. The steps, however, are yours to choose.",
  "Your struggles are fading away. It’s time to move forward.",
  "Your desires are ready to manifest. But are you ready?",
  "Nothing happens too early or too late. Trust the process.",
  "Maybe the road feels long so you can be sure of what you truly want.",
  "Love is in the details. To see it, you must look with your heart.",
  "Abundance, prosperity, and new opportunities are at the door. You decide how to welcome them.",
  "Success is pouring down like rain. Don’t lose yourself. ;)",
  "The universe is not rushing you — but the green light is already on.",
  "Money is testing you: if you have a plan, it stays.",
  "This time love arrives not with noise, but with a quiet touch.",
  "The voice inside you is no longer whispering — it speaks clearly. Listen.",
  "This year the ‘maybes’ decrease and the ‘I knows’ increase.",
  "You take one step, destiny takes two.",
  "Fatigue leaves, lightness takes its place.",
  "Opportunities that match your rhythm are slowly approaching.",
  "Your choices are magical — because they are conscious.",
  "This year you are the calmest and strongest version of yourself.",
  "Your manifestation is working; the result is finding its way.",
  "The knots of destiny are untangling — not with your hands, but with your heart.",
  "The dream you see tonight will not be a coincidence.",
  "Old energy is leaving, making space for a new beginning.",
  "Magic is working — the universe is just having its coffee. A little patience.",
  "Your wish has been granted; the universe says ‘processing…’",
  "Abundance is at the door, and you’re still in pajamas. It’s okay.",
  "Money is coming — but first, your self-belief update is downloading.",
  "The universe is not testing you, it’s simply getting to know you.",
  "Your intuition is right again. Yes, you’re right — again.",
  "Destiny’s message to you is short: ‘Relax. I’m here.’",
];