export const FORTUNES = [
"Pul səni gözləyir — qapını açmaq vaxtıdır.",
  "Sevgi bu il sənə məktub yox, isti şal bağışlayacaq. Emosiyaların güclənir",
  "Karyera yolun aydınlaşır — artıq sən öz yolundasan.",
  "Güzgü artıq sənə sadəcə baxmır, alqışlayır. Parlayırsan.",
  "Şansın elə parlayacaq ki, hər addımın işıq saçacaq.",
  "Bir fincan isti çay = arzuya bir addım daha yaxın.",
  "Taleyin pıçıldayır: 'Sən hazır olanda mən də hazıram.'",
  "Bu il bir az sehr, bir az cəsarət, bir az da darçın qoxusu gətirir. Bərəkətlənirsən",
  "Diləyin gerçəkləşsə, təəccüblənmə. Gerçəkləşməsə, daha yaxşısı gəlir.",
  "Kainat sənə göz qırpır. Mesajlara qarşı ayıq ol.",
  "Pul artıq sənin planına uyğun axır.",
  "Sevgi bu il səni tapıb — sadəcə qucaq aç.",
  "Bu il işin keyfiyyətini sən özün görəcəksən.",
  "Üzündəki gülüş ən güclü sehr olacaq.",
  "Pul artıq səni tərk etmir, yanında qalır.",
  "Sevgi sənə sual yox, cavab verir. İşlərinə sevgi qat",
  "Yavaş-yavaş, amma möhkəm irəliləyirsən.",
  "Həyatında yeni səhifələr açılır, yeniliklər ən yüksək xeyrinə olsun.",
  "Bu il görünüşün daxili parıltınla birlikdə işıldayır.",
  "Özünü seçmək eqoizm deyil, özünə qayğıdır.",
  "Pul sənin ritminə uyğun axır.",
  "Ən güclü sehr: davamlılıq və sakitlikdir.",
  "Sənin olan səninlə qalır. Qalanlarını isə burax.",
  "Sənin olan artıq sənə gəlir, sadəcə görüş təyin etməlisən.",
  "Nəhayət burulğandan çıxırsan, təbrik edirəm.",
  "Məncə cavabı özün bilirsən. Bəlkə hərəkətə keçəsən? ;)",
  "Bu il özünə güvənmək sənə yol göstərəcək.",
  "Yeni başlanğıclar səni gözləyir.",
"Diləyin qəbul oldu, sadəcə kainat 'loading...' yazır.",
"Yağış səsləri sənə mesaj daşıyır: doğru yol səsli yox, sakit olur.",
"Üzündəki gülüş bu il ən güclü manifest olacaq.",
 "Pul bu il ciblərə yox, planlara axır. Planını qur.",
  "Sevgi bu il isti çay kimidir — yavaş iç, dadını al.",
"Bu il ən yaxşı qərar: özünə qulaq asmaq olacaq.",
"İç səsinə güvən. Bütün cavablar gözünün qarşısındadır.",
"Yolun aydınlanır. Addımlarını isə özün seçəcəksən.",
"Sıxıntıların yox olub gedir. Artıq irəliləmək vaxtıdır",
"İstəklərin reallaşmağa hazırdır. Bəs sən buna hazırsanmı?",
"Heç nə gec və ya tez baş vermir. Prosesə güvən",
"Yolun uzanmağı, bəlkə də istədiyindən əmin olmağın üçündür.",
"Sevgi detallardadır. Onu görə bilmək üçün isə ürək gözü ilə baxmalısan.",
"Bolluq, bərəkət, yeni fürsətlər qapıdadır. Necə qarşılayacağına özün qərar ver.",
"Uğurların yağış kimi yağır. Özünü itirmə. ;)",
"Kainat səni tələsdirmir — amma artıq yaşıl işıq yanıb.",
"Pul səni yoxlayır: planın varsa, qalır.",
"Sevgi bu dəfə səs-küylə yox, sakit bir toxunuşla gəlir.",
"İçindəki səs artıq pıçıldamır — aydın danışır. Dinlə.",
"Bu il “bəlkə”lər azalır, “mən bilirəm”lər artır.",
"Bir addım atırsan, tale iki addım gəlir.",
"Yorğunluq gedir, yerini yüngüllük tutur.",
"Sənin ritminə uyğun fürsətlər yavaş-yavaş yaxınlaşır.",
"Seçimlərin sehrlidir — çünki şüurludur.",
"Bu il sən öz həyatının ən sakit, ən güclü versiyasısan.",
"Manifestin işləyir, nəticə yolunu tapır.",
"Taleyin düyünləri açılır— əllərinlə deyil, ürəyinlə.",
"Bu gecə gördüyün yuxu təsadüf olmayacaq.",
"Köhnə enerji gedir, yerini yeni başlanğıc tutur.",
"Sehr işləyir, sadəcə kainat da qəhvəsini içir — azca səbir.",
"Diləyin qəbul olundu, kainat isə ‘processing…’ deyir.",
"Bərəkət qapıdadır, sən isə hələ pijamadasan. Problem deyil.",
"Pul gəlir, amma əvvəlcə özünə inanma update-i yüklənir.",
"Kainat səni test etmir, sadəcə səni tanıyır.",
"Bu dəfə də hisslərin düz çıxır. Bəli, yenə sən haqlısan.",
"Taleyin sənə mesajı qısadır: ‘Relax. Mən buradayam.’",
];
